{{- if .Values.phpldapadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ldap-stack.phpldapadmin.fullname" . }}
  labels:
    {{- include "ldap-stack.phpldapadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ldap-stack.phpldapadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ldap-stack.phpldapadmin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: phpldapadmin
          image: "{{ .Values.phpldapadmin.image.repository }}:{{ .Values.phpldapadmin.image.tag }}"
          imagePullPolicy: {{ .Values.phpldapadmin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: {{ include "ldap-stack.openldap.fullname" . }}
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.phpldapadmin.resources | nindent 12 }}
      {{- with .Values.phpldapadmin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.phpldapadmin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.phpldapadmin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
